### ISSUE TITLE
`getenvoy run` to start the latest version by default

### ISSUE THREAD

**Issue by rakyll** [tetratelabs/getenvoy#106]
`getenvoy run` requires users to set a target as an argument but target names are verbose. I find myself often having to `getenvoy list` to copy/paste the target name in development time. Would it be reasonable if `getenvoy run` was running the latest version compatible to the host platform by default? If users want to use specific a version/platform, they can keep passing an argument.

**Comment by codefromthecrypt** [comment]
I agree and confirm that the current version doesn't do this and it should

**Comment by codefromthecrypt** [comment]
we could possibly also shortcut a minimal config like so:

```bash
$ getenvoy run standard:1.17.1 -- --config-yaml "admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}}"
```

so that doing `getenvoy run` does the same thing..


https://github.com/tetratelabs/getenvoy/pull/182/files#r615385360

**Comment by codefromthecrypt** [comment]
I think basically we should fetch the manifest and rank the latest version present. The only other way is to use the "last known" build which will be out of date as soon as getenvoy cli is cut. ex currently it is "1.17.1" The latter approach is more stable, but has a risk of being out of date. In any case, we can fallback to this. any thoughts?

**Comment by codefromthecrypt** [comment]
Here's an idea cc @anuraaga who helped collaborate

1. switch to a `getenvoy use` model: remove the version arg from `getenvoy run` completely. This also removes arg ambiguity
2. Default to the version in ~/.getenvoy/envoy-version. If not present persist envoy_versions.json/latestVersion and install it.
3. To support parallel use, first look at $PWD/.envoy-version

In the future, we can add `getenvoy upgrade` which could fetch the latest patch or upgrade the version entirely. There are some scenarios where blind upgrading doesn't work. Another way is to support "N.N.x" syntax in the version file, which will always check for latest patch. We don't have to do this now, but this is thinking ahead.

**Comment by codefromthecrypt** [comment]
while bike shed, I'm kindof partial to .envoy_version vs .envoy-version just to match envoy_versions.json. That or switch the file convention of envoy_versions.json to envoy-versions.json

**Comment by nacx** [comment]
I like the idea of `getenvoy use`, especially for development environments. This is similar to other tooling that is becoming popular like `rbenv`, `jenv`, etc. configuring it once and being able to quickly run it is great.

**Comment by nacx** [comment]
Just thinking out loud here:
Talking about running it fast with just a `getenvoy run`, would it make sense to configure by default the `config-path` to, say, the current directory? Or something the `getenvoy use` could configure. and have the `$PWD/.envoy-version` contain the version and the path to the config file?

**Comment by jcchavezs** [comment]
I think I like much better the `use`/`run` combo, defaulting to latest version could be a confusing experience because that could change without the user to easily find it out. Pinning the version with the `use` command makes it explicit and I guess the `run` command can always display the version being run along with the source of the version (filepath for the envoy_version file).

**Comment by codefromthecrypt** [comment]
@nacx thanks for the comment. I'll  make some notes

> Talking about running it fast with just a getenvoy run, would it make sense to configure by default the config-path to, say, the current directory? Or something the getenvoy use could configure. and have the $PWD/.envoy-version contain the version and the path to the config file?

So the main trick here is that getenvoy isn't written in bash, like some of the tools I mentioned.. They change the PATH mostly on 'use' and indeed we now have a choice how to handle that.

`use` aside, I think for `run`, we can look first in $PWD/.envoy-version falling back to $HOME/.getenvoy/envoy-version

For `use`, we could go the same order, persisting to $PWD/.envoy-version (if present) falling back to $HOME/.getenvoy/envoy-version by default.

I think the main trick is whether to create $PWD/.envoy-version when it doesn't exist, and I think no (by default). Unlike git, nvm etc, there's no workspace concept. The PWD of the person invoking getenvoy is arbitrary and not actually used by envoy at runtime, either.

TL'DR' I think we should update $HOME/.getenvoy unless $PWD/.envoy-version already exists on `getenvoy use`.

We can help people avoid `cat 1.18.3 > .envoy-version` if we like, by adding an optional flag to `getenvoy use`. I'm on the fence about doing this, but not bothered by adding this except that we're forced to then name that flag :D. 🔫 to my head, I would follow git and use `--local` or `--global` as options to clarify beyond the default behavior.

Any other thoughts?

**Comment by codefromthecrypt** [comment]
ps there's already a GETENVOY_HOME (default to $HOME/.getenvoy) which is why I wasn't proposing a config file location option.. simplest would be PWD and GETENVOY_HOME for file choices. Worst case we can re-add a cavaot'ed --envoy-version param or something to `getenvoy run` as that's less complicated than a third persistence choice. I wouldn't go there until we get some users asking for it though, as flags aren't easy to remove later and they always tend to accumulate.

**Comment by codefromthecrypt** [comment]
pps going to rename [envoy_versions.json](https://raw.githubusercontent.com/tetratelabs/getenvoy/master/site/envoy_versions.json) to envoy-versions.json in a separate change,  so that we have parity with the .envoy-version file. There wasn't any thought into the case format and I think it is better to hyphen it before release. If anyone would be upset about this, please speak up or forever hold your underscores

**Comment by llinder** [comment]
Adding `getenvoy use` and removing the need for the version flag on `run` would be a nice improvement. 

> I think the main trick is whether to create $PWD/.envoy-version when it doesn't exist, and I think no (by default).

I agree that if we support local/workspace config it should be opt-in and default should be to use global.  @codefromthecrypt WDYT of `--global` being default unless local config is already present and then requiring users to specify one of `--global` or `--local`?  It makes documentation a bit more work but should be fairly safe way to have local config without users always having to think about it upfront.

**Comment by codefromthecrypt** [comment]
works for me. thanks for the feedback folks. I'll raise a PR so we can finally ship this!

**Comment by codefromthecrypt** [comment]
fyi looked at https://github.com/jenv/jenv, it uses local vs global also for the thing except it makes them separate commands. This is good to solidify terms, though I think use with flags is neater as it allows inference.

```
   local       Set or show the local application-specific Java version
   global      Set or show the global Java version
```

**Comment by codefromthecrypt** [comment]
jenv was originally derived from pyenv/rbenv I guess so has the same commands

**Comment by nacx** [comment]
>nacx thanks for the comment. I'll make some notes

If I read your comment correctly I think I expressed it incorrectly or it was misunderstood. I wasn't talking about the config path for getenvoy itself, but for the final Envoy configuration file. The one you must pass every time with `-- --config...` and saving users to always pass that so they can just `getenvoy run`, and have that pick a config.yaml in the current directory (or making that default envoy config file configurable via getenvoy use as well). It was just a thought on providing a no-args `getenvoy run`

**Comment by codefromthecrypt** [comment]
@nacx gotcha in our tests we just start the admin server. we can add something like that also

**Comment by codefromthecrypt** [comment]
I think the summary of concern here is how to handle the default version. There are two main ways

1. be explicit
2. be implicit

The issue as requested was literally asking to be implicit. Make `getenvoy run -c envoy.yaml` use the latest version. No steps. no needing to learn where config is stored. just do it.

Being explicit would in extreme teaching first the side effects and local/global jargon inherited from git, perhaps stumbling the whole way:

`getenvoy run` .. oh you need to install something. `getenvoy install X`.. great. `getenvoy run` oh you need to choose a version.. humm.. I see "local and global"  why no remote? OHH local means PWD. got it. I know oh there's a file in my directory now.. ok.. what was I doing? right.. `getenvoy run` wow I'm a pro now, certify me!

The more I've thought about this the more I think being explicit by default isn't coherent with the goal here ... which is to be implicit and easy. make it easy on people by having fewer wrong turns to get started, ideally none.

`getenvoy use 1.18.3` updates the first thing it finds, either in the PWD or in the ENVOY_HOME. That or a different word like "default" but the same idea.

(It is true that `use` is not the best word, and someone not familiar with nvm may wonder what it is. People who know `nvm use` may also not like it because this doesn't implement PATH override! However, that this is not great doesn't mean we should invert the design)

The good news is we don't actually need to do any of this. We can just make `getenvoy run` lookup the version from getenvoy.io each time and completely punt any concept of defaulting versions to something local (ps the home dir is still local :))

Just it feels like this is being lazy and worth doing right. I still think https://github.com/tetratelabs/getenvoy/issues/106#issuecomment-848868073 is the best way forward: `getenvoy use 1.18.3` which updated the home dir if a working dir file is missing. I'd prefer to implement this knowing the pros and cons, I think it is the better pill.

Someone who hates this can alias `getenvoy local` to `getenvoy use --local`. In fact they might alias `gel`.. people sometimes have really short aliases. Meanwhile, we'll have shell autocompletion soon to help bank those keystrokes. There's no plan to have any two commands share a letter, so this shouldn't be too hard on the fingers one way or another!

**Comment by codefromthecrypt** [comment]
Since this touches a few things, I summarizes the plan here and will give a stab tomorrow https://github.com/tetratelabs/getenvoy/issues/248

**Comment by codefromthecrypt** [comment]
@rakyll you are probably ignoring by now, but apologies for the super long delay. https://github.com/tetratelabs/getenvoy/pull/251 fixes this!
