### ISSUE TITLE
Rename default extension.json to extension.config

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/getenvoy#124]
While writing [TinyGo tutorial](https://github.com/tetratelabs/getenvoy.io/pull/155), I realized that we should not limit extension configuration to be json, also the name `extension.json` sounds ambiguous to me because it does not have a `configuration`-ish word in its name. 

So I would like to rename it to be `extension.config` or something similar which does not indicate the format and have config-ish meaning in its name. Ideas? @yskopets @nullpo-head 

As a workaround for the format, we can add `data/example/init/templates/envoy..../${format}/*` which contains `extension.${format}` for every template, but I think that's too much just for resolving this.

**Comment by yskopets** [comment]
@mathetake I can try to explain motivation behind the current solution (and naming).

Envoy configuration model allows developers of Wasm extensions to choose any format for their own configuration.

That's why `getenvoy` allows developers to do the same - we accept configuration from files named:
* `extension.yaml`
* `extension.json`
* `extension`

See https://github.com/tetratelabs/getenvoy/blob/master/pkg/extension/workspace/model/example.go#L85

We could add `extension.config` to that list. Or `extension.txt`. Or something else.

The reason why we always generate `extension.json` is to steer extension developers in the right direction. We want ecosystem of Wasm extensions to be consistent. Unless there is a very good reason not to use JSON, developers should stick to JSON by default.

In the case of `(Tiny)Go`, I would still generate `extension.json` by default. And explain in the `Getting Started` that a developer can:
* either add support for JSON (this is always a preferred way)
* or rename configuration file into `extension` (or `extension.config`, or `extension.txt`, if we add support for those names)

Regarding the name `extension.json`, it happens that file with Envoy bootstrap config is commonly called `envoy.yaml`.

So, my approach to naming was "if a file with Envoy bootstrap configuration is called `envoy.yaml`, then it's logical to call file with extension configuration `extension.yaml`/`extension.json`".

I'm open for changes.

**Comment by mathetake** [comment]
I'm OK with renaming the file (in the generation phase) to something like that only for TinyGo. But I have some concerns that would make the getenvoy's code needlessly complicated. WDYT?

**Comment by yskopets** [comment]
If you want to rename this file for `(Tiny)Go`, please go ahead. No concerns about complexity.

My personal preference would be `extension.txt` or `extension.env`. Then `extension.config`.

Let's update the source code of the init template(s) to support comment lines in the config file.

And then include a comment line into `extension.txt` / `extension.env` / `extension.config` explaining why we use a non-JSON format.

You will also need to update examples' `README.md` files, e.g. https://github.com/tetratelabs/getenvoy/blob/master/data/example/init/templates/envoy.access_loggers/default/README.md
