### ISSUE TITLE
ci: significant regression in run time of `e2e` tests on MacOS

### ISSUE THREAD

**Issue by yskopets** [tetratelabs/getenvoy#140]
**Describe the bug**

* prior to https://github.com/tetratelabs/getenvoy/pull/135, the run time of `e2e` tests on MacOS was about `~42 min`, e.g. [here](https://github.com/tetratelabs/getenvoy/runs/2189593019)
* after https://github.com/tetratelabs/getenvoy/pull/135, the run time of `e2e` tests on MacOS is `3+ hours` and counting, e.g. [here](https://github.com/tetratelabs/getenvoy/runs/2198918254?check_suite_focus=true) and [here](https://github.com/tetratelabs/getenvoy/runs/2199262800?check_suite_focus=true)

**To Reproduce**
1. Check out the run time of CI `Run e2e tests on MacOS` job since https://github.com/tetratelabs/getenvoy/pull/135

**Expected behavior**
* As a contributor, I would prefer faster feedback from `e2e` tests

**Screenshots**
* <img width="1122" alt="Screenshot 2021-03-26 at 08 42 53" src="https://user-images.githubusercontent.com/19395458/112598694-42b8e800-8e0f-11eb-881c-bdf6bc4e440c.png">
* <img width="1179" alt="Screenshot 2021-03-26 at 08 42 01" src="https://user-images.githubusercontent.com/19395458/112598628-2452ec80-8e0f-11eb-85f8-bbecb77cf009.png">

**Comment by codefromthecrypt** [comment]
note before #135 <https://github.com/tetratelabs/getenvoy/pull/135> just
the installation part of docker for mac routinely hung on PRs, which is why
I looked at it in the first place.

>

**Comment by codefromthecrypt** [comment]
specifically, it would hang on the output "Waiting for docker service to be in the running state"

**Comment by yskopets** [comment]
* Is a CI build that takes `3,5+ hours` instead of `42min` better ?
* Why #135 was merged without waiting until CI build completes successfully ?

**Comment by codefromthecrypt** [comment]
before this merged even docker install wouldn't finish.

https://github.com/tetratelabs/getenvoy/runs/2198242029?check_suite_focus=true

there are significant problems in that setup. I chatted with @mathetake and knowing that's the case, merged based on unix success. I think you also know there are significant issues in and outside CI with osx #88.

Once tests are in better shape in general I don't mind polishing this, but it isn't something I'm going to do knowing the runners will be different soon anyway. Feel free to look at it, but don't think #135 was done for no reason. you can't run e2e until you can install osx.

**Comment by yskopets** [comment]
Is it the conclusion?

CI build will take `3,5+ hours` from now on ?

**Comment by mathetake** [comment]
I think that’s because you pushed tons of commits and tons of mac provisioning job happening in GitHub actions.

**Comment by mathetake** [comment]
Sorry, ^ that maybe not the case

**Comment by codefromthecrypt** [comment]
very likely @mathetake I had the same thought. the same setup was able to build a docker image (ex the part preceding e2e), it seems docker is working. when I looked at one of the hung jobs it was stuck on a rust compile line. that's usually a hint of a resource problem. I'm not sure the nature of the parallel things, but since that's changing anyway was hoping we can proceed until things quiet, then afterwards look deeper at it as necessary.

The only main change I can see from the setup was that formerly a pinned docker version was used. I put a test PR #141 but as the queue backlog is what it is, I don't expect this to run soon. In fact presence of that PR might make things worse, but worth a shot.

**Comment by codefromthecrypt** [comment]
forked #143 about general problems with things taking too long (even the linux side)

**Comment by yskopets** [comment]
@codefromthecrypt I see that the old way of running `e2e` tests on `Mac` takes `42 min` as before. E.g. [here](https://github.com/tetratelabs/getenvoy/runs/2201066082)

While the new way takes `3,5+ hours`.

We haven't competed a single build on `master` after merging #135.

I'd like to ask you to revert #135 for now.

**Comment by yskopets** [comment]
I think https://github.com/tetratelabs/getenvoy/pull/142 should be enough for now until #135 is improved.

**Comment by codefromthecrypt** [comment]
I don't have access to revert anything, or even approve.

However, I did verify that at some point last night the timeouts on the old script stopped. Hopefully they don't come back!

Reverting #135 wasn't needed because only the osx install script part effected anything. I made notes in that issue about what went wrong.

I raised https://github.com/tetratelabs/getenvoy/pull/146 which uses the pinned script and also has your commit on it that adds timeouts.

I also raised #145 about the pinned docker as the setup is fragile and pinning to old docker walks around the problem in a way that isn't explained fully. However, looking deeply at that can be deferred since other test setup changes are in progress. If the timeout during install thing happens again, your thing will stop the build and it can be re-kicked in the Actions UI.

Regardless, thanks for the help!

**Comment by codefromthecrypt** [comment]
FYI The install script is failing again in exactly the same way that led to #135 in the first place. It failed last night and also just now.

That said, I'm fine personally as having the old script work sometimes is better than having the new one fail all the time.

I'm not interested in fighting over this as I do think things will improve as long as I or someone else has time to get to the bottom of things.
